name: Mobile Test Automation - Calendar App

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Choose the test suite to run'
        required: true
        default: 'CalendarRegression'
        type: choice
        options:
          - CalendarRegression
          - WheelPickerRegression

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        run: mvn test -Dtest.suite=${{ inputs.test_suite }}.xml